//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MercadoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        public int idProduto { get; set; }
        public string Nome { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<int> categoriaProduto { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
